export const services = [
  {
    slug: "mvp-development",
    name: "MVP development",
    title: "Freelance MVP Developer for Startups",
    description: "Turn your startup idea into a working MVP with Muaath Rifath. Full-stack development, authentication, payments, and deployment scoped around your first users.",
    intro: "I build MVPs for founders who want to test a product idea. We choose the features needed for a first release, then build and launch them.",
    fit: "For founders testing a new business idea, teams replacing a manual process, or businesses launching a new digital product. We start by identifying the one workflow your first users need to complete, then decide what belongs in the first release.",
    deliverables: ["A core user journey with responsive screens and a working backend", "User accounts, permissions, and a database shaped around your product", "Payments, third-party APIs, or AI features where the scope needs them", "Deployment, source code handover, and a plan for the next iteration"],
    approach: "We map the user journey, separate essential features from later ideas, and agree on milestones. You review working demos throughout development. Before launch, we check the key flows and deployment setup, then use what you learn from real users to prioritize improvements.",
    question: "How much does an MVP cost, and how long does it take?",
    answer: "The scope determines the budget and schedule: user roles, screens, integrations, and existing assets all matter. Send a short description of the problem, your must-have features, and any deadline. I can then estimate the work and suggest what to include in the first release.",
  },
  {
    slug: "website-development",
    name: "Website development",
    title: "Freelance Website Developer in Chennai",
    description: "Custom business websites and landing pages by Muaath Rifath, a freelance web developer in Chennai. Responsive development, technical SEO, and inquiry forms.",
    intro: "I build business websites and landing pages, including service pages, contact forms, and content you can update yourself.",
    fit: "For service businesses that need more relevant inquiries, founders preparing a launch, and teams whose existing website no longer reflects their work. I’m based in Chennai and can work remotely with your team wherever you are.",
    deliverables: ["Responsive pages for your services, company, and contact information", "Clear navigation and calls to action matched to your business goals", "Technical SEO foundations: page metadata, crawlable content, and a sitemap", "Contact forms, analytics or CMS integration when included in the scope"],
    approach: "We identify your main audience and the action visitors should take. From there, we organize the pages, agree on content and design, and build the site. I check mobile layouts, accessibility basics, and the inquiry flow before helping with deployment and handover.",
    question: "Can you improve an existing website?",
    answer: "Yes. Share the current URL and explain what is getting in the way: outdated content, difficult updates, mobile issues, slow pages, or missing functionality. I can review the existing setup and scope a focused improvement or a rebuild based on what makes sense.",
  },
  {
    slug: "ecommerce-development",
    name: "Ecommerce development",
    title: "Freelance Ecommerce Website Developer",
    description: "Build an ecommerce website with Muaath Rifath: product catalogs, shopping carts, payment integrations, and order workflows scoped around your business.",
    intro: "I build online stores with product listings, a shopping cart, checkout, and order management.",
    fit: "For businesses starting to sell online or needing functionality their current store cannot support. We work through your products, payment options, delivery process, and administrative needs before choosing the implementation.",
    deliverables: ["Product listings and detail pages designed for mobile and desktop", "Cart and checkout flows with a suitable payment provider", "Order management and customer notifications as agreed in the scope", "Product metadata, indexable category pages, and deployment support"],
    approach: "We map the buying journey alongside what happens after an order is placed. The build covers the agreed storefront and integrations, followed by checks for payment success, failed payments, and order states. Shipping, tax, refunds, and inventory requirements are scoped explicitly with you.",
    question: "Do I need a custom store or an existing ecommerce platform?",
    answer: "That depends on your catalog, budget, integrations, and who will manage the store. We can assess an existing platform before committing to custom development. A custom build makes sense when your workflows need capabilities that a standard setup cannot comfortably support.",
  },
  {
    slug: "custom-software-development",
    name: "Custom software & integrations",
    title: "Freelance Custom Software Developer",
    description: "Hire Muaath Rifath for custom web applications, APIs, dashboards, workflow automation, and AI integrations. Technical solutions built around your business.",
    intro: "I build internal tools, dashboards, and custom applications. I can also connect existing systems, automate repetitive tasks, or add AI features.",
    fit: "For teams coordinating work across spreadsheets and disconnected tools, products that need a new backend capability, or businesses with a technical problem that does not fit an off-the-shelf solution.",
    deliverables: ["Internal dashboards, admin tools, or custom web applications", "APIs and integrations between your existing systems", "Background jobs, document processing, and workflow automation", "AI and voice features, access controls, and deployment as scoped"],
    approach: "We start with the workflow and its constraints: who uses it, what data moves through it, and what happens when something fails. I define the interfaces and access rules, build in reviewable milestones, and test the critical paths with you before handover.",
    question: "Can you work with my existing codebase or tools?",
    answer: "Yes. Share the stack, the problem, and the systems that need to connect. I’ll review the relevant code and integration constraints before proposing a scope. If a smaller integration or configuration change solves the problem, we can start there.",
  },
] as const;
